### ISSUE TITLE
Please do not include external libs

### ISSUE THREAD

**Issue by pcav** [unacast/bigquerylayers#12]
And leave the user install it autonomously.
Thanks.

**Comment by smandaric** [comment]
We tried this initially, but it turned out to be too complicated. Our initial approach was that the plugin user installs pip and Google Cloud SDK in their QGIS python interpreter. The main issue was that everyone's QGIS install was different (especially on MacOS), so we couldn't find a standard process to install the dependencies.

Including external libs was the only user-friendly approach we could find. 

Can you point me to some examples of plugins using external python libraries?

Thanks

**Comment by pcav** [comment]
Yes, this is a long standing problem for qgis plugins. There have been several discussions about how to implement automatic installation from the plugin itself, but we did reach a firm conclusion.

**Comment by smandaric** [comment]
Yep, I can't seem to find a standard approach of doing this. One approach would be to run some install scripts but that would require too much support and maintenance. I suggest releasing the plugin in it's current form and revisiting when a conclusion is reached.

**Comment by smandaric** [comment]
I have not found a good approach for not including external libs. I will leave the libs.

**Comment by pcav** [comment]
I still think these should not be included. See similar discussions for other plugins.
Thanks for understanding.
